#!/bin/bash
set -e

echo "=== EXPANSE OS CHROOT FINAL ==="
USER="expanse"
BASE="/home/$USER/workspace"

echo "=== BASE SYSTEM ==="
pacman -S --noconfirm \
  efibootmgr \
  hyprland xdg-desktop-portal-hyprland kitty \
  pipewire pipewire-pulse wireplumber \
  wl-clipboard xdg-utils

systemctl enable NetworkManager

echo "=== SYSTEMD-BOOT INSTALL ==="
bootctl install
mkdir -p /boot/loader/entries

cat <<EOF > /boot/loader/loader.conf
default expanse
timeout 3
editor no
EOF

ROOT_UUID=$(blkid -s UUID -o value $(findmnt -n -o SOURCE /))

cat <<EOF > /boot/loader/entries/expanse.conf
title   Expanse OS
linux   /vmlinuz-linux
initrd  /initramfs-linux.img
options root=UUID=$ROOT_UUID rw
EOF

# Sincroniza o kernel instalado com o gerenciador de boot
mkinitcpio -p linux

echo "=== USER SETUP ==="
if ! id "$USER" &>/dev/null; then
    useradd -m -G wheel $USER
fi
echo "$USER:expanse" | chpasswd
sed -i '/%wheel ALL=(ALL:ALL) ALL/d' /etc/sudoers
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

echo "=== AUTO LOGIN ==="
mkdir -p /etc/systemd/system/getty@tty1.service.d
cat <<EOF > /etc/systemd/system/getty@tty1.service.d/override.conf
[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --autologin $USER --noclear %I \$TERM
EOF

echo "=== AUTO START HYPRLAND ==="
cat <<EOF > /home/$USER/.bash_profile
if [[ -z \$WAYLAND_DISPLAY ]] && [[ \$(tty) == /dev/tty1 ]]; then
    exec Hyprland
fi
EOF
chown $USER:$USER /home/$USER/.bash_profile

echo "=== HYPRLAND CONFIG (SHELL MODE) ==="
mkdir -p /home/$USER/.config/hypr

cat <<EOF > /home/$USER/.config/hypr/hyprland.conf
autogenerated = 0 

# Dispara o inicializador do seu ambiente Tauri
exec-once = $BASE/expanse-shell/start-dev.sh

# Regra de Janela: Força qualquer janela do Tauri a iniciar em Fullscreen
windowrulev2 = fullscreen, class:^(expanse-shell)$
windowrulev2 = fullscreen, title:^(expanse-shell)$

# Regra para o Terminal sobreposto: Torna ele flutuante e centralizado
windowrulev2 = float, class:^(kitty)$
windowrulev2 = size 70% 60%, class:^(kitty)$
windowrulev2 = center, class:^(kitty)$

# ATALHOS DO SISTEMA
# Super + T: Abre o Terminal do Arch sobreposto à sua interface Tauri
bind = SUPER, T, exec, kitty
# Super + Q: Fecha o Hyprland (Sair do OS)
bind = SUPER, Q, exit
EOF

chown -R $USER:$USER /home/$USER/.config
echo "Configuração do chroot concluída!"
